-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 13:43:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banana_hitec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banana_hitec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banana_hitec` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `banana_hitec`;

-- -----------------------------------------------------
-- Table `banana_hitec`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`grupos` (
  `id_grupo` BIGINT NOT NULL,
  `descricao` TEXT NOT NULL,
  `nome` TEXT NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;



-- -----------------------------------------------------
-- Table `banana_hitec`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`tokens` (
  `token` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`token`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `banana_hitec`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`administradores` (
  `id_adm` BIGINT NOT NULL,
  `codenome` VARCHAR(146) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `data_engressou` DATETIME NOT NULL,
  `ultimo_login` DATETIME NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '0',
  `fk_id_grupo` BIGINT NULL DEFAULT NULL,
  `fk_token` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_adm`),
  UNIQUE INDEX `fk_token_UNIQUE` (`fk_token` ASC) ,
  INDEX `fk_id_grupo` (`fk_id_grupo` ASC),
  CONSTRAINT `administradores_ibfk_1`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`),
  CONSTRAINT `administradores_ibfk_2`
    FOREIGN KEY (`fk_token`)
    REFERENCES `banana_hitec`.`tokens` (`token`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `banana_hitec`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`permissoes` (
  `id_permissao` BIGINT NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `codinome` VARCHAR(146) NOT NULL,
  PRIMARY KEY (`id_permissao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `banana_hitec`.`permissoes_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`permissoes_grupos` (
  `pk_permissao` BIGINT NOT NULL,
  `pk_grupo` BIGINT NOT NULL,
  PRIMARY KEY (`pk_permissao`, `pk_grupo`),
  INDEX `fK_id_permissao` (`pk_permissao` ASC),
  INDEX `fk_id_grupo` (`pk_grupo` ASC),
  CONSTRAINT `permissoes_grupos_ibfk_1`
    FOREIGN KEY (`pk_permissao`)
    REFERENCES `banana_hitec`.`permissoes` (`id_permissao`),
  CONSTRAINT `permissoes_grupos_ibfk_2`
    FOREIGN KEY (`pk_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`vendedores` (
  `cnpj` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_fantasia` TEXT NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `data_engressou` DATETIME NOT NULL,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `fk_grupo` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fk_id_grupo` (`fk_grupo` ASC),
  CONSTRAINT `vendedores_ibfk_1`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`produtos` (
  `id_produto` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `tipo_produto` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `peso` DECIMAL(5,2) NOT NULL,
  `qtd` INT NOT NULL DEFAULT '1',
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `url_foto` VARCHAR(255) NULL DEFAULT NULL,
  `fk_vendedor` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `produtos_ibfk_1_idx` (`fk_vendedor` ASC),
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`fk_vendedor`)
    REFERENCES `banana_hitec`.`vendedores` (`cnpj`))
ENGINE = InnoDB
AUTO_INCREMENT = 407
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`usuarios` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_usuario` TEXT NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `primeiro_nome` TINYTEXT NOT NULL,
  `sobrenome` TEXT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefone` BIGINT NOT NULL,
  `sexo` ENUM('f', 'm') NOT NULL,
  `cpf` BIGINT NOT NULL,
  `data_engressou` DATETIME NOT NULL,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT '0',
  `fk_grupo` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_id_grupo` (`fk_grupo` ASC),
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
