-- MySQL Script generated by MySQL Workbench
-- Sat Sep 14 17:46:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banana_hitec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banana_hitec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banana_hitec` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `banana_hitec` ;

-- -----------------------------------------------------
-- Table `banana_hitec`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`grupos` (
  `id_grupo` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(146) NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`administradores` (
  `id_admin` BIGINT NOT NULL,
  `codenome` VARCHAR(146) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `data_engressou` DATETIME NOT NULL,
  `ultimo_login` DATETIME NOT NULL,
  `status` TINYINT NOT NULL DEFAULT '0',
  `fk_id_grupo` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_admin`),
  INDEX `fk_id_grupo` (`fk_id_grupo` ASC) VISIBLE,
  CONSTRAINT `administradores_ibfk_1`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`permissoes` (
  `id_permissao` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `codinome` VARCHAR(146) NOT NULL,
  PRIMARY KEY (`id_permissao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`permissoes_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`permissoes_grupos` (
  `id_permissao_grupo` BIGINT NOT NULL,
  `fk_id_permissao` BIGINT NOT NULL,
  `fk_id_grupo` BIGINT NOT NULL,
  PRIMARY KEY (`id_permissao_grupo`),
  INDEX `fK_id_permissao` (`fk_id_permissao` ASC) VISIBLE,
  INDEX `fk_id_grupo` (`fk_id_grupo` ASC) VISIBLE,
  CONSTRAINT `permissoes_grupos_ibfk_1`
    FOREIGN KEY (`fk_id_permissao`)
    REFERENCES `banana_hitec`.`permissoes` (`id_permissao`),
  CONSTRAINT `permissoes_grupos_ibfk_2`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`vendedores` (
  `cnpj` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_fantasia` VARCHAR(146) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `data_engressou` DATETIME NOT NULL,
  `ultimo_login` DATETIME NOT NULL,
  `fk_id_grupo` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fk_id_grupo` (`fk_id_grupo` ASC) VISIBLE,
  CONSTRAINT `vendedores_ibfk_1`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`produtos` (
  `id_produto` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(146) NOT NULL,
  `tipo_produto` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `peso` DECIMAL(5,2) NOT NULL,
  `qtd` INT NOT NULL DEFAULT '1',
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `url_foto` VARCHAR(255) NULL DEFAULT NULL,
  `fk_vendedores` BIGINT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `produtos_ibfk_1_idx` (`fk_vendedores` ASC) VISIBLE,
  CONSTRAINT `#produtos_ibfk_1`
    FOREIGN KEY (`fk_vendedores`)
    REFERENCES `banana_hitec`.`vendedores` (`cnpj`))
ENGINE = InnoDB
AUTO_INCREMENT = 383
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banana_hitec`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banana_hitec`.`usuarios` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(146) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `primeiro_nome` VARCHAR(50) NOT NULL,
  `sobrenome` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefone` BIGINT NOT NULL,
  `sexo` ENUM('f', 'm', 'h') NOT NULL,
  `cpf` BIGINT NOT NULL,
  `data_engressou` DATETIME NOT NULL,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT '0',
  `fk_id_grupo` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_id_grupo` (`fk_id_grupo` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `banana_hitec`.`grupos` (`id_grupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
